name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Build Executable
      run: pyinstaller main.py --onefile

    - name: Rename built exe to MicrosipTool.exe
      run: mv dist/main.exe dist/MicrosipTool.exe

    - name: Generate version.json
      run: python generate_version_json.py ${{ github.ref_name }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/MicrosipTool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish version.json to gh-pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        cp version.json gh-pages/
        cd gh-pages
        git add version.json
        git commit -m "Update version.json for ${{ github.ref_name }}"
        git push
