name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller main.py --onefile --distpath dist

      - name: Rename executable
        run: mv dist/main dist/MicrosipTool.exe

      - name: Generate version.json
        run: python generate_version_json.py ${{ github.ref_name }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MicrosipTool.exe
            version.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload version.json to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          destination_dir: .
